// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feoebdljsqxvcqtyxlur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlb2ViZGxqc3F4dmNxdHl4bHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MjEzMzQsImV4cCI6MjA3Njk5NzMzNH0.etZxW3Achec_2uspGdP4KI_cLwqKaR7avQkOVr2SGAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});